services:
  price-backend:
    build: ./backend
    container_name: price-backend
    environment:
      PROD: ${PROD}
      API_PORT: 3000
      API_URL: http://localhost
      DATABASE_HOST: price-db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - uploads:/app/uploads
    depends_on:
      - price-db
    networks:
      - backend

  price-db:
    image: postgres:13
    container_name: price-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - price_db_data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    build: ./frontend
    container_name: price-frontend
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: price-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads:/uploads
    depends_on:
      - frontend
      - price-backend
    networks:
      - backend

networks:
  backend:

volumes:
  price_db_data:
  uploads:
