services:
  - type: web
    name: pl-price-api-backend
    env: docker
    repo: https://github.com/Queue-Evgenii/pl-price-api-admin
    branch: main
    dockerfilePath: ./backend/Dockerfile
    buildCommand:
    startCommand:
    envVars:
      - key: API_PORT
        value: "3000"
      - key: DATABASE_HOST
        value: pl-price-api-db
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_USER
        value: postgres
      - key: DATABASE_PASSWORD
        value: 1111
      - key: DATABASE_NAME
        value: pl-price-api
      - key: JWT_SECRET
        value: 25b008a8dfa3eebcb33e99b05747df85aea8c4c629d3c15a9ba1c017402b096d
    ports:
      - containerPort: 3000
    dependsOn:
      - pl-price-api-db

  - type: database
    name: pl-price-api-db
    env: postgres
    plan: free
    user: postgres
    password: 1111
    databaseName: pl-price-api
    region: oregon

  - type: web
    name: pl-price-api-frontend
    env: docker
    repo: https://github.com/Queue-Evgenii/pl-price-api-admin
    branch: main
    dockerfilePath: ./frontend-admin/Dockerfile
    buildCommand:
    startCommand:
    ports:
      - containerPort: 80
    dependsOn:
      - pl-price-api-backend
