server {
    listen 80;

    location / {
        proxy_pass http://price-frontend:80;
    }

    location /api/ {
        proxy_pass http://price-backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        proxy_pass http://price-backend:3000/uploads/;
    }

    location /static/ {
        proxy_pass http://price-backend:3000/static/;
    }
}
